### ISSUE TITLE
Failing ARM test cases in "armwrestler.gba"

### ISSUE THREAD

**Issue by daniel5151** [daniel5151/armv4t_emu#1]
Running `armwrestler.gba` in [my fork of gba-rs](https://github.com/daniel5151/gba-rs/tree/cpu-from-crate) indicates that `arm7tdmi-rs` is failing several ARM-mode test cases. THUMB-mode seems to work fine though.

**Comment by sean-purcell** [comment]
Partially fixed, looking into the LDM one now.

**Comment by sean-purcell** [comment]
Looking at the armwrestler source, I think armwrestler is just wrong on the LDM stuff.  According to https://www.akkit.org/info/gbatek.htm#arm11blockdatatransferldmstm, the LDM behaviour is different for ARMv5 vs ARMv4.  Since this emulator is v4, and afaik armwrestler was originally for DS (v5), the behaviour difference is expected.
